version: '3.8'

services:
  frosthaven:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frosthaven
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./public/img:/usr/share/nginx/html/img

  fh-api:
    build:
      context: ./fh-api
      dockerfile: Dockerfile
    container_name: fh-api
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - ./fh-api/data:/app/data
    env_file:
      - ./fh-api/.env
